version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres-spring
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydata
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./file-postgres.sql:/docker-entrypoint-initdb.d/file-postgres.sql
#    networks:
#      - net-postgres-spring
  pgadmin:
    image: dpage/pgadmin4
    container_name: spring_pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abdennour.ouassini1981@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
#    networks:
#      - net-postgres-spring
  backend:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    image: nor/spring-simple
    ports:
      - "1200:1200"
    container_name: spring-simple-v1
    restart: always
#    volumes:
#      - pg-data:/backend
#    networks:
#      - net-postgres-spring
volumes:
  pg-data:
  pgadmin-data:
#    name: pg-data
#networks:
#  net-postgres-spring:
#    driver: bridge
#    name: net-postgres-spring