#spring.config.import=h2.properties
spring.config.import=postgres-docker.properties
#my.property=value
#java -jar simple.jar --spring.config.location=optional:classpath:h2.properties
#java -jar simple.jar --spring.config.location=./h2.properties